package com.lawfirm.management.appointment;

import com.lawfirm.management.appointment.dto.*; import com.lawfirm.management.client.*; import com.lawfirm.management.common.audit.*; import com.lawfirm.management.common.exception.*; import com.lawfirm.management.legalcase.*; import com.lawfirm.management.user.*;
import com.lawfirm.management.common.audit.Auditable;
import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDateTime; import java.util.UUID;

@Service @RequiredArgsConstructor
public class AppointmentService {
 private final AppointmentRepository repository; private final UserRepository userRepository; private final LegalCaseRepository legalCaseRepository; private final ClientRepository clientRepository; private final AppointmentMapper mapper;
 @Transactional(readOnly=true) public Page<AppointmentResponse> list(AppointmentStatus status,Pageable pageable,User current){ Page<Appointment> p=current.getRole()==Role.ADVOGADO?(status==null?repository.findAllByAssignedUserId(current.getId(),pageable):repository.findAllByAssignedUserIdAndStatus(current.getId(),status,pageable)):(status==null?repository.findAll(pageable):repository.findAllByStatus(status,pageable)); return p.map(mapper::toResponse); }
 @Transactional(readOnly=true) public AppointmentResponse findById(UUID id,User current){return mapper.toResponse(getAccessible(id,current));}
 @Transactional @Auditable(action=AuditAction.CREATE,entityName="Appointment",description="Compromisso cadastrado.") public AppointmentResponse create(CreateAppointmentRequest r,User current){validateDates(r.startsAt(),r.endsAt()); User assigned=resolveAssignee(r.assignedUserId(),current); LegalCase legalCase=resolveCase(r.legalCaseId()); Client client=resolveClient(r.clientId()); validateRelations(legalCase,client); ensureNoConflict(assigned,r.startsAt(),null); Appointment e=Appointment.builder().title(r.title().trim()).description(normalize(r.description())).startsAt(r.startsAt()).endsAt(r.endsAt()).location(normalize(r.location())).type(r.type()==null?AppointmentType.MEETING:r.type()).status(AppointmentStatus.SCHEDULED).assignedUser(assigned).legalCase(legalCase).client(client).build(); return mapper.toResponse(repository.save(e)); }
 @Transactional @Auditable(action=AuditAction.UPDATE,entityName="Appointment",description="Compromisso atualizado.") public AppointmentResponse update(UUID id,UpdateAppointmentRequest r,User current){Appointment e=getAccessible(id,current);validateDates(r.startsAt(),r.endsAt());User assigned=resolveAssignee(r.assignedUserId(),current);LegalCase lc=resolveCase(r.legalCaseId());Client c=resolveClient(r.clientId());validateRelations(lc,c);if(r.status()!=AppointmentStatus.CANCELLED)ensureNoConflict(assigned,r.startsAt(),id);e.setTitle(r.title().trim());e.setDescription(normalize(r.description()));e.setStartsAt(r.startsAt());e.setEndsAt(r.endsAt());e.setLocation(normalize(r.location()));e.setType(r.type()==null?AppointmentType.MEETING:r.type());e.setStatus(r.status());e.setAssignedUser(assigned);e.setLegalCase(lc);e.setClient(c);return mapper.toResponse(repository.save(e));}
 @Transactional @Auditable(action=AuditAction.COMPLETE,entityName="Appointment",description="Compromisso concluído.") public AppointmentResponse complete(UUID id,User current){Appointment e=getAccessible(id,current);if(e.getStatus()==AppointmentStatus.CANCELLED)throw new BusinessException("Um compromisso cancelado não pode ser concluído.");e.setStatus(AppointmentStatus.COMPLETED);return mapper.toResponse(repository.save(e));}
 @Transactional @Auditable(action=AuditAction.UPDATE,entityName="Appointment",description="Compromisso cancelado.") public AppointmentResponse cancel(UUID id,User current){Appointment e=getAccessible(id,current);if(e.getStatus()==AppointmentStatus.COMPLETED)throw new BusinessException("Um compromisso concluído não pode ser cancelado.");e.setStatus(AppointmentStatus.CANCELLED);return mapper.toResponse(repository.save(e));}
 private Appointment getAccessible(UUID id,User u){Appointment e=repository.findById(id).orElseThrow(()->ResourceNotFoundException.of("Compromisso",id));if(u.getRole()==Role.ADVOGADO&&!u.getId().equals(e.getAssignedUser().getId()))throw new ForbiddenOperationException("Você não possui acesso a este compromisso.");return e;}
 private User resolveAssignee(UUID id,User current){UUID effective=id;if(current.getRole()==Role.ADVOGADO){if(id!=null&&!current.getId().equals(id))throw new ForbiddenOperationException("Um advogado só pode atribuir o compromisso a si mesmo.");effective=current.getId();}if(effective==null)throw new BusinessException("O responsável pelo compromisso é obrigatório.");final UUID resolvedId=effective;User u=userRepository.findById(resolvedId).orElseThrow(()->ResourceNotFoundException.of("Responsável",resolvedId));if(!u.isActive()||(u.getRole()!=Role.ADVOGADO&&u.getRole()!=Role.ASSISTENTE))throw new BusinessException("O responsável informado não é um advogado ou assistente ativo.");return u;}
 private LegalCase resolveCase(UUID id){return id==null?null:legalCaseRepository.findById(id).orElseThrow(()->ResourceNotFoundException.of("Processo",id));}
 private Client resolveClient(UUID id){return id==null?null:clientRepository.findById(id).orElseThrow(()->ResourceNotFoundException.of("Cliente",id));}
 private void validateRelations(LegalCase lc,Client c){if(lc!=null&&lc.getStatus()==LegalCaseStatus.CLOSED)throw new BusinessException("Não é possível agendar compromisso em processo encerrado.");if(c!=null&&!c.isActive())throw new BusinessException("Não é possível agendar compromisso para cliente inativo.");if(lc!=null&&c!=null&&!lc.getClient().getId().equals(c.getId()))throw new BusinessException("O cliente informado não pertence ao processo selecionado.");}
 private void validateDates(LocalDateTime s,LocalDateTime e){if(s==null||e==null||!e.isAfter(s))throw new BusinessException("A data final deve ser posterior à data inicial.");}
 private void ensureNoConflict(User u,LocalDateTime start,UUID id){boolean conflict = id == null ? repository.existsByAssignedUserIdAndStartsAtAndStatusNot(u.getId(), start, AppointmentStatus.CANCELLED) : repository.existsByAssignedUserIdAndStartsAtAndStatusNotAndIdNot(u.getId(), start, AppointmentStatus.CANCELLED, id);
  if(conflict) throw new BusinessException("Já existe um compromisso para este responsável neste horário.");}
 private String normalize(String v){return v==null||v.isBlank()?null:v.trim();}
}
